import type { EmergencyCase, EmergencyPersistedState, HospitalUnit, SeverityRole, SystemAlert } from './emergency-types'

export const roleDefaults: Record<SeverityRole, string> = {
  Critical: 'Hospital A',
  Burn: 'Hospital B',
  Moderate: 'Hospital C',
  Minor: 'Hospital D',
}

const initialHospitals: HospitalUnit[] = [
  { name: 'Hospital A', status: 'Yellow', acceptsIncoming: true, icu: 5, general: 8, doctors: 12, specializations: ['Trauma', 'Burn', 'Neuro'], capacity: 68, x: 78, y: 26 },
  { name: 'Hospital B', status: 'Green', acceptsIncoming: true, icu: 12, general: 18, doctors: 15, specializations: ['Cardiology', 'Trauma'], capacity: 42, x: 22, y: 80 },
  { name: 'Hospital C', status: 'Yellow', acceptsIncoming: true, icu: 3, general: 5, doctors: 8, specializations: ['General', 'Burn'], capacity: 78, x: 88, y: 78 },
  { name: 'Hospital D', status: 'Green', acceptsIncoming: true, icu: 8, general: 14, doctors: 10, specializations: ['General', 'Neuro'], capacity: 35, x: 14, y: 16 },
]

const initialCases: EmergencyCase[] = [
  {
    id: 1001,
    type: 'Multiple vehicle accident',
    location: 'Downtown Main Street',
    status: 'Active',
    victims: 12,
    timeAgo: 5,
    severity: { Critical: 3, Burn: 2, Moderate: 4, Minor: 3 },
    suggestedHospitals: { ...roleDefaults },
    timeline: [
      { time: '14:05', event: 'Call received - multi-vehicle accident' },
      { time: '14:06', event: 'Ambulances dispatched (5 units)' },
      { time: '14:08', event: 'First responders on scene' },
      { time: '14:12', event: 'Initial triage generated by AI' },
    ],
  },
]

const initialAlerts: SystemAlert[] = [
  { id: 'a1', title: 'O- Blood Low', detail: 'Only 3 units remaining', priority: 'Critical', createdAt: Date.now() - 10000 },
  { id: 'a2', title: 'Hospital A Capacity', detail: '85% bed occupancy', priority: 'High', createdAt: Date.now() - 8000 },
]

export function getDefaultEmergencyState(): EmergencyPersistedState {
  return {
    cases: initialCases,
    ambulances: [
      { id: 'AM-01', role: 'Critical', status: 'En Route', assignedHospital: 'Hospital A', etaMin: 3, x: 35, y: 36 },
      { id: 'AM-02', role: 'Moderate', status: 'En Route', assignedHospital: 'Hospital C', etaMin: 5, x: 45, y: 42 },
      { id: 'AM-03', role: 'Minor', status: 'Available', assignedHospital: 'Hospital D', etaMin: 0, x: 20, y: 18 },
      { id: 'AM-04', role: 'Critical', status: 'Busy', assignedHospital: 'Hospital A', etaMin: 0, x: 73, y: 28 },
      { id: 'AM-05', role: 'Burn', status: 'En Route', assignedHospital: 'Hospital B', etaMin: 8, x: 56, y: 60 },
      { id: 'AM-06', role: 'Burn', status: 'Available', assignedHospital: 'Hospital B', etaMin: 0, x: 25, y: 66 },
      { id: 'AM-07', role: 'Moderate', status: 'Available', assignedHospital: 'Hospital C', etaMin: 0, x: 84, y: 67 },
      { id: 'AM-08', role: 'Minor', status: 'Available', assignedHospital: 'Hospital D', etaMin: 0, x: 30, y: 24 },
    ],
    hospitals: initialHospitals,
    alerts: initialAlerts,
    activeCaseId: 1001,
    bloodUnits: { oNegative: 3, abNegative: 4 },
  }
}
