'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type SeverityRole = 'Critical' | 'Burn' | 'Moderate' | 'Minor'
export type AlertPriority = 'Critical' | 'High' | 'Medium'

export interface EmergencyCase {
  id: number
  type: string
  location: string
  status: 'Active' | 'In Progress'
  victims: number
  timeAgo: number
  severity: Record<SeverityRole, number>
  timeline: { time: string; event: string }[]
  suggestedHospitals: Record<SeverityRole, string>
}

export interface AmbulanceUnit {
  id: string
  role: SeverityRole
  status: 'En Route' | 'Available' | 'Busy'
  assignedHospital: string
  etaMin: number
  x: number
  y: number
}

export interface HospitalUnit {
  name: string
  status: 'Green' | 'Yellow' | 'Red'
  acceptsIncoming: boolean
  icu: number
  general: number
  doctors: number
  specializations: string[]
  capacity: number
  x: number
  y: number
}

export interface SystemAlert {
  id: string
  title: string
  detail: string
  priority: AlertPriority
  createdAt: number
}

interface EmergencyContextValue {
  cases: EmergencyCase[]
  ambulances: AmbulanceUnit[]
  hospitals: HospitalUnit[]
  alerts: SystemAlert[]
  activeCaseId: number
  bloodUnits: { oNegative: number; abNegative: number }
  aiLoading: boolean
  createCase: (payload: { location: string; caseType: string; estimatedVictims: number; description: string }) => void
  setActiveCase: (caseId: number) => void
  runAITriage: (caseId?: number) => void
  reassignAmbulance: (ambulanceId: string, role: SeverityRole, hospital: string) => void
  applyRecommendation: () => void
  redirectAmbulances: () => void
  requestBloodUnits: () => void
  toggleHospitalIntake: (hospitalName: string) => void
}

const EmergencyContext = createContext<EmergencyContextValue | undefined>(undefined)

const roleDefaults: Record<SeverityRole, string> = {
  Critical: 'Hospital A',
  Burn: 'Hospital B',
  Moderate: 'Hospital C',
  Minor: 'Hospital D',
}

const initialHospitals: HospitalUnit[] = [
  { name: 'Hospital A', status: 'Yellow', acceptsIncoming: true, icu: 5, general: 8, doctors: 12, specializations: ['Trauma', 'Burn', 'Neuro'], capacity: 68, x: 78, y: 26 },
  { name: 'Hospital B', status: 'Green', acceptsIncoming: true, icu: 12, general: 18, doctors: 15, specializations: ['Cardiology', 'Trauma'], capacity: 42, x: 22, y: 80 },
  { name: 'Hospital C', status: 'Yellow', acceptsIncoming: true, icu: 3, general: 5, doctors: 8, specializations: ['General', 'Burn'], capacity: 78, x: 88, y: 78 },
  { name: 'Hospital D', status: 'Green', acceptsIncoming: true, icu: 8, general: 14, doctors: 10, specializations: ['General', 'Neuro'], capacity: 35, x: 14, y: 16 },
]

const initialAmbulances: AmbulanceUnit[] = [
  { id: 'AM-01', role: 'Critical', status: 'En Route', assignedHospital: 'Hospital A', etaMin: 3, x: 35, y: 36 },
  { id: 'AM-02', role: 'Moderate', status: 'En Route', assignedHospital: 'Hospital C', etaMin: 5, x: 45, y: 42 },
  { id: 'AM-03', role: 'Minor', status: 'Available', assignedHospital: 'Hospital D', etaMin: 0, x: 20, y: 18 },
  { id: 'AM-04', role: 'Critical', status: 'Busy', assignedHospital: 'Hospital A', etaMin: 0, x: 73, y: 28 },
  { id: 'AM-05', role: 'Burn', status: 'En Route', assignedHospital: 'Hospital B', etaMin: 8, x: 56, y: 60 },
  { id: 'AM-06', role: 'Burn', status: 'Available', assignedHospital: 'Hospital B', etaMin: 0, x: 25, y: 66 },
  { id: 'AM-07', role: 'Moderate', status: 'Available', assignedHospital: 'Hospital C', etaMin: 0, x: 84, y: 67 },
  { id: 'AM-08', role: 'Minor', status: 'Available', assignedHospital: 'Hospital D', etaMin: 0, x: 30, y: 24 },
]

const initialCases: EmergencyCase[] = [
  {
    id: 1001,
    type: 'Multiple vehicle accident',
    location: 'Downtown Main Street',
    status: 'Active',
    victims: 12,
    timeAgo: 5,
    severity: { Critical: 3, Burn: 2, Moderate: 4, Minor: 3 },
    suggestedHospitals: { ...roleDefaults },
    timeline: [
      { time: '14:05', event: 'Call received - multi-vehicle accident' },
      { time: '14:06', event: 'Ambulances dispatched (5 units)' },
      { time: '14:08', event: 'First responders on scene' },
      { time: '14:12', event: 'Initial triage generated by AI' },
    ],
  },
]

export function EmergencyProvider({ children }: { children: React.ReactNode }) {
  const [cases, setCases] = useState<EmergencyCase[]>(initialCases)
  const [activeCaseId, setActiveCaseId] = useState(1001)
  const [ambulances, setAmbulances] = useState<AmbulanceUnit[]>(initialAmbulances)
  const [hospitals, setHospitals] = useState<HospitalUnit[]>(initialHospitals)
  const [alerts, setAlerts] = useState<SystemAlert[]>([
    { id: 'a1', title: 'O- Blood Low', detail: 'Only 3 units remaining', priority: 'Critical', createdAt: Date.now() - 10000 },
    { id: 'a2', title: 'Hospital A Capacity', detail: '85% bed occupancy', priority: 'High', createdAt: Date.now() - 8000 },
  ])
  const [bloodUnits, setBloodUnits] = useState({ oNegative: 3, abNegative: 4 })
  const [aiLoading, setAiLoading] = useState(false)

  const addAlert = (title: string, detail: string, priority: AlertPriority) => {
    setAlerts((prev) =>
      [{ id: `${Date.now()}-${Math.random()}`, title, detail, priority, createdAt: Date.now() }, ...prev]
        .sort((a, b) => {
          const rank = { Critical: 3, High: 2, Medium: 1 }
          return rank[b.priority] - rank[a.priority] || b.createdAt - a.createdAt
        })
        .slice(0, 8)
    )
  }

  const getBestAcceptingHospital = (fallbackName: string) => {
    const accepting = hospitals.filter((h) => h.acceptsIncoming)
    if (accepting.length === 0) return fallbackName
    const preferred = accepting.find((h) => h.name === fallbackName)
    if (preferred) return preferred.name
    return [...accepting].sort((a, b) => a.capacity - b.capacity)[0].name
  }

  const runAITriage = (caseId = activeCaseId) => {
    setAiLoading(true)
    setTimeout(() => {
      setCases((prev) =>
        prev.map((c) => {
          if (c.id !== caseId) return c
          const severeShift = Math.max(1, Math.round(c.victims * 0.25))
          const moderateShift = Math.max(1, Math.round(c.victims * 0.35))
          const burnShift = Math.max(1, Math.round(c.victims * 0.15))
          const minorShift = Math.max(1, c.victims - severeShift - moderateShift - burnShift)
          return {
            ...c,
            severity: { Critical: severeShift, Burn: burnShift, Moderate: moderateShift, Minor: minorShift },
            suggestedHospitals: { ...roleDefaults },
            timeline: [
              ...c.timeline,
              {
                time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                event: 'AI triage run: severity, role assignment, and hospital allocation updated',
              },
            ],
          }
        })
      )
      setAmbulances((prev) =>
        prev.map((unit, index) => {
          const roles: SeverityRole[] = ['Critical', 'Burn', 'Moderate', 'Minor']
          const role = roles[index % roles.length]
          return {
            ...unit,
            role,
            assignedHospital: getBestAcceptingHospital(roleDefaults[role]),
            status: 'En Route',
            etaMin: Math.max(2, (index % 6) + 2),
          }
        })
      )
      addAlert('AI Triage Completed', `Case #${caseId} synchronized across triage, ambulance, and hospital modules`, 'High')
      setAiLoading(false)
    }, 1200)
  }

  const createCase = (payload: { location: string; caseType: string; estimatedVictims: number; description: string }) => {
    const newId = Math.max(...cases.map((c) => c.id)) + 1
    const nextCase: EmergencyCase = {
      id: newId,
      type: payload.caseType || 'Emergency',
      location: payload.location || 'Unknown location',
      status: 'Active',
      victims: Math.max(1, payload.estimatedVictims),
      timeAgo: 0,
      severity: { Critical: 1, Burn: 1, Moderate: 2, Minor: 1 },
      suggestedHospitals: { ...roleDefaults },
      timeline: [
        { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), event: 'Case created by command center operator' },
        { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), event: payload.description || 'No description provided' },
      ],
    }
    setCases((prev) => [nextCase, ...prev])
    setActiveCaseId(newId)
    addAlert('New Emergency Case', `Case #${newId} created at ${nextCase.location}`, 'High')
    runAITriage(newId)
  }

  const reassignAmbulance = (ambulanceId: string, role: SeverityRole, hospital: string) => {
    const assignedHospital = getBestAcceptingHospital(hospital)
    setAmbulances((prev) =>
      prev.map((unit) =>
        unit.id === ambulanceId ? { ...unit, role, assignedHospital, status: 'En Route', etaMin: Math.max(2, unit.etaMin || 4) } : unit
      )
    )
  }

  const redirectAmbulances = () => {
    const targetHospital = getBestAcceptingHospital('Hospital B')
    setAmbulances((prev) =>
      prev.map((unit) => (unit.role === 'Moderate' ? { ...unit, assignedHospital: targetHospital, etaMin: unit.etaMin + 2 } : unit))
    )
    addAlert('Ambulances Redirected', `Moderate severity units rerouted to ${targetHospital}`, 'High')
  }

  const requestBloodUnits = () => {
    setBloodUnits((prev) => ({ oNegative: prev.oNegative + 20, abNegative: prev.abNegative + 15 }))
    addAlert('Blood Units Requested', 'Emergency replenishment request sent for O- and AB-', 'Critical')
  }

  const toggleHospitalIntake = (hospitalName: string) => {
    setHospitals((prev) =>
      prev.map((hospital) =>
        hospital.name === hospitalName ? { ...hospital, acceptsIncoming: !hospital.acceptsIncoming } : hospital
      )
    )
    const current = hospitals.find((h) => h.name === hospitalName)
    const nextState = current ? !current.acceptsIncoming : false
    addAlert(
      'Hospital Intake Updated',
      `${hospitalName} is now ${nextState ? 'accepting incoming cases' : 'diverting incoming cases'}`,
      'Medium'
    )
  }

  const applyRecommendation = () => {
    redirectAmbulances()
    requestBloodUnits()
    addAlert('Recommendation Applied', 'AI recommendation package executed successfully', 'High')
  }

  useEffect(() => {
    const timer = setInterval(() => {
      setAmbulances((prev) =>
        prev.map((unit) => {
          if (unit.status !== 'En Route') return unit
          const hospital = initialHospitals.find((h) => h.name === unit.assignedHospital)
          if (!hospital) return unit
          const dx = hospital.x - unit.x
          const dy = hospital.y - unit.y
          const nx = Math.abs(dx) < 0.8 ? hospital.x : unit.x + Math.sign(dx) * 0.8
          const ny = Math.abs(dy) < 0.8 ? hospital.y : unit.y + Math.sign(dy) * 0.8
          const reached = Math.abs(dx) < 1 && Math.abs(dy) < 1
          return {
            ...unit,
            x: nx,
            y: ny,
            etaMin: reached ? 0 : Math.max(1, unit.etaMin - 1),
            status: reached ? 'Busy' : unit.status,
          }
        })
      )
      setHospitals((prev) =>
        prev.map((h) => {
          const delta = Math.random() > 0.5 ? 1 : -1
          const capacity = Math.max(20, Math.min(97, h.capacity + delta))
          const status: HospitalUnit['status'] = capacity > 88 ? 'Red' : capacity > 70 ? 'Yellow' : 'Green'
          return { ...h, capacity, status }
        })
      )
      setCases((prev) => prev.map((c) => ({ ...c, timeAgo: c.timeAgo + 1 })))
    }, 3000)
    return () => clearInterval(timer)
  }, [])

  const value = useMemo(
    () => ({
      cases,
      ambulances,
      hospitals,
      alerts,
      activeCaseId,
      bloodUnits,
      aiLoading,
      createCase,
      setActiveCase: setActiveCaseId,
      runAITriage,
      reassignAmbulance,
      applyRecommendation,
      redirectAmbulances,
      requestBloodUnits,
      toggleHospitalIntake,
    }),
    [cases, ambulances, hospitals, alerts, activeCaseId, bloodUnits, aiLoading]
  )

  return <EmergencyContext.Provider value={value}>{children}</EmergencyContext.Provider>
}

export function useEmergency() {
  const ctx = useContext(EmergencyContext)
  if (!ctx) throw new Error('useEmergency must be used within EmergencyProvider')
  return ctx
}
